# Generated by Django 5.0.6 on 2024-06-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeyevents',
            name='qualifying_criteria',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
